### ISSUE TITLE
`ansible-galaxy collection install` fails due to missing manifest.json

### ISSUE THREAD

**Issue by hhenkel** [ansible-collections/vmware.vmware_rest#166] opened 2020-11-03 12:06 UTC
##### SUMMARY
Downloaded the ```vmware.vmware_rest-1.0.1.tar.gz``` file from the [ansible automation hub](https://cloud.redhat.com/ansible/automation-hub/vmware/vmware_rest) to do a local install as my environment is disconnected. When trying to install the downloaded file, I get an error as shown below.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
collection

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.10.2
  config file = None
  configured module search path = ['/home/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/myuser/ansible/venv/lib64/python3.6/site-packages/ansible
  executable location = /home/myuser/ansible/venv/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION
```

```

##### OS / ENVIRONMENT
RHEL 8 / CENTOS 8

##### STEPS TO REPRODUCE
```
$ ansible-galaxy collection install ~/vmware.vmware_rest-1.0.1.tar.gz
Starting galaxy collection install process
Process install dependency map
ERROR! Collection at '/home/myuser/vmware.vmware_rest-1.0.1.tar.gz' does not contain the required file MANIFEST.json.
```

##### EXPECTED RESULTS
Collection is installed in the current working directory

##### ACTUAL RESULTS
```
ERROR! Collection at '/home/myuser/vmware.vmware_rest-1.0.1.tar.gz' does not contain the required file MANIFEST.json.
```

**Comment by goneri** [comment] 2020-11-03 16:29
I cannot reproduce the problem. Are you sure the file is not corrupted? Can you compare with your installation:

```
[goneri@t580-gone Downloads]$ sha256sum vmware-vmware_rest-1.0.1.tar.gz
297358d05551bd104eb94be40edaa14dd55ea9f9a2f3953f58f0197689536c7d  vmware-vmware_rest-1.0.1.tar.gz
```

Also, since you're off-line, the collection depend on another collection called `cloud.common`, you need to grab this archive too.

**Comment by hhenkel** [comment] 2020-11-06 07:57
Hi @goneri,
thanks for the response - I looked at the sha256 checksum of the file and you're right, I get a different value. I downloaded it again from the website and this time it seems fine. I'm not entirely sure what went wrong the first time, maybe some issue with the proxy/scanning of the file. Are the checksums of the files available as well somewhere?

**Comment by goneri** [comment] 2020-11-25 21:08
Hi @hhenkel,

Nothing I'm aware of regarding the checksum. I close the issue since the problem is resolved.

**Closed by goneri** 2020-11-25 21:08 UTC
