### ISSUE TITLE
vmware.vmware_rest.datastore_moid

### ISSUE THREAD

**Issue by StefanSchwiedel** [ansible-collections/vmware.vmware_rest#343] opened 2022-06-20 11:30 UTC
Trying to lookup the datastore or ESX host moid always (really in any case) fails with the same error.
Reproducable on fresh installations

**Module Version:** vmware-vmware_rest-2.1.5

**OS:** Redhat 7.9
ansible-playbook 2.9.27
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.8 (default, Aug 13 2020, 07:46:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

**OS:** Debian 11
ansible-playbook 2.10.8
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]

```
Package            Version
--------------------------
aiohttp               3 .8.1
```

### Ansible Playbook
```
- name: debug datastore moid
   vars:
      connection_args:
        vcenter_hostname: "vcenter.test"
        vcenter_username: "administrator@vsphere.local"
        vcenter_password: "1234"
   debug:
      msg: "{{ lookup('vmware.vmware_rest.datastore_moid', '/datacenter_name/datastore/datastore_name', connection_args) }}"

```

### ERROR Message
`An unhandled exception occurred while running the lookup plugin 'vmware.vmware_rest.datastore_moid'. Error was a <class 'RecursionError'>, original message: maximum recursion depth exceeded while pickling an object`

**Comment by mikemorency** [comment] 2024-09-09 16:47
Recent changes to  the lookup plugin structure have resolved this type of error. Testing with the plugins yields results for the example in this issue. Im going to close this, feel free to re-open or open a new issue if the issue is persisting for you

See https://github.com/ansible-collections/vmware.vmware_rest/issues/500 for relevant conversation and the expected release date for the fix

**Closed by mikemorency** 2024-09-09 16:47 UTC
Labels: bug
