### ISSUE TITLE
vmware.vmware_rest_vcenter_vm_info module JSONDecodeError

### ISSUE THREAD

**Issue by jsy-m** [ansible-collections/vmware.vmware_rest#428] opened 2023-10-27 06:03 UTC
##### SUMMARY

I'm using vmware.vmware_rest_vcenter_vm_info module on awx 17.1.0 ,
when i play workflow template, sometime "JSONDecodeError" causing problem. 

playbook hosts are usually 5-6 nodes

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.11]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/my-envs/lotte-mysql-venv/lib64/python3.8/site-packages/ansible
  ansible collection location = /var/lib/awx/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/my-envs/lotte-mysql-venv/bin/ansible
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
vmware.vmware_rest 2.3.1
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS 8

##### STEPS TO REPRODUCE

Gathering vm info with folder information.

```yaml
        - name: "Parsing {{ db_service_nm }} Vcenter Folder"
          vmware.vmware_rest.vcenter_folder_info:
            filter_names:
              - "{{ db_service_nm }}"
          register: my_folder_info

        - name: "Search {{ inventory_hostname }} Guest Server"
          register: search_result
          vmware.vmware_rest.vcenter_vm_info:
            filter_folders:
              - "{{ my_folder_info.value[0].folder }}"
            filter_names:
              - "{{ inventory_hostname }}"
```

##### EXPECTED RESULTS

"module_args": {
      "filter_folders": [
        "group-v4806"
      ],
      "filter_names": [
        "test1"
      ],
      "vcenter_hostname": "",
      "vcenter_username": "",
      "vcenter_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "vcenter_validate_certs": false,
      "folders": [
        "group-v4806"
      ],
      "names": [
        "test1"
      ],
      "vcenter_rest_log_file": null,
      "session_timeout": null,
      "clusters": null,
      "datacenters": null,
      "hosts": null,
      "power_states": null,
      "resource_pools": null,
      "vm": null,
      "vms": null
    }

##### ACTUAL RESULTS

```"module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_vmware.vmware_rest.vcenter_vm_info_payload__j724qy0/ansible_vmware.vmware_rest.vcenter_vm_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py\", line 106, in communicate\n  File \"/usr/lib64/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib64/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib64/python3.8/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1698385329.0733624-3526-262145398530803/AnsiballZ_vcenter_vm_info.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1698385329.0733624-3526-262145398530803/AnsiballZ_vcenter_vm_info.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1698385329.0733624-3526-262145398530803/AnsiballZ_vcenter_vm_info.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.vmware.vmware_rest.plugins.modules.vcenter_vm_info', init_globals=dict(_module_fqn='ansible_collections.vmware.vmware_rest.plugins.modules.vcenter_vm_info', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_vmware.vmware_rest.vcenter_vm_info_payload__j724qy0/ansible_vmware.vmware_rest.vcenter_vm_info_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/vcenter_vm_info.py\", line 474, in <module>\n  File \"/usr/lib64/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n    return future.result()\n  File \"/tmp/ansible_vmware.vmware_rest.vcenter_vm_info_payload__j724qy0/ansible_vmware.vmware_rest.vcenter_vm_info_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/vcenter_vm_info.py\", line 403, in main\n  File \"/tmp/ansible_vmware.vmware_rest.vcenter_vm_info_payload__j724qy0/ansible_vmware.vmware_rest.vcenter_vm_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py\", line 119, in __init__\n  File \"/tmp/ansible_vmware.vmware_rest.vcenter_vm_info_payload__j724qy0/ansible_vmware.vmware_rest.vcenter_vm_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py\", line 154, in run_on_daemon\n  File \"/tmp/ansible_vmware.vmware_rest.vcenter_vm_info_payload__j724qy0/ansible_vmware.vmware_rest.vcenter_vm_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py\", line 109, in communicate\nansible_collections.cloud.common.plugins.module_utils.turbo.exceptions.EmbeddedModuleUnexpectedFailure: Cannot decode plugin answer: b''\n",
  "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_vmware.vmware_rest.vcenter_vm_info_payload__j724qy0/ansible_vmware.vmware_rest.vcenter_vm_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py\", line 106, in communicate\n  File \"/usr/lib64/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib64/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib64/python3.8/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1698385329.0733624-3526-262145398530803/AnsiballZ_vcenter_vm_info.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1698385329.0733624-3526-262145398530803/AnsiballZ_vcenter_vm_info.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1698385329.0733624-3526-262145398530803/AnsiballZ_vcenter_vm_info.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.vmware.vmware_rest.plugins.modules.vcenter_vm_info', init_globals=dict(_module_fqn='ansible_collections.vmware.vmware_rest.plugins.modules.vcenter_vm_info', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_vmware.vmware_rest.vcenter_vm_info_payload__j724qy0/ansible_vmware.vmware_rest.vcenter_vm_info_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/vcenter_vm_info.py\", line 474, in <module>\n  File \"/usr/lib64/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n    return future.result()\n  File \"/tmp/ansible_vmware.vmware_rest.vcenter_vm_info_payload__j724qy0/ansible_vmware.vmware_rest.vcenter_vm_info_payload.zip/ansible_collections/vmware/vmware_rest/plugins/modules/vcenter_vm_info.py\", line 403, in main\n  File \"/tmp/ansible_vmware.vmware_rest.vcenter_vm_info_payload__j724qy0/ansible_vmware.vmware_rest.vcenter_vm_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py\", line 119, in __init__\n  File \"/tmp/ansible_vmware.vmware_rest.vcenter_vm_info_payload__j724qy0/ansible_vmware.vmware_rest.vcenter_vm_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py\", line 154, in run_on_daemon\n  File \"/tmp/ansible_vmware.vmware_rest.vcenter_vm_info_payload__j724qy0/ansible_vmware.vmware_rest.vcenter_vm_info_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/common.py\", line 109, in communicate\nansible_collections.cloud.common.plugins.module_utils.turbo.exceptions.EmbeddedModuleUnexpectedFailure: Cannot decode plugin answer: b''\n",
  "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
```

**Comment by gravesm** [comment] 2023-11-13 19:05
Likely duplicate of #356

**Comment by machacekondra** [comment] 2024-03-12 11:36
Closing, as it's duplicate of #356

**Closed by machacekondra** 2024-03-12 11:36 UTC
