### ISSUE TITLE
vmware api explorer vcenter 6.7u2 does not know vmware.vmware_rest.vcenter_vm_tools_info

### ISSUE THREAD

**Issue by RobVerduijn** [ansible-collections/vmware.vmware_rest#152] opened 2020-10-19 09:57 UTC
##### SUMMARY

the rest api explorer for vmware vcenter 6.7u2 does not know the endpoint http://{vcenter}/rest/vcenter/vm/{vm}/tools
thus the module always fails

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by goneri** [comment] 2020-10-21 17:28
This REST end-point was not available in this version. The module are tested on 7.0.0.

**Comment by goneri** [comment] 2020-10-22 14:39
I close the issue since it's not a bug, but a limitation of vsphere 6.3 itself.

**Closed by goneri** 2020-10-22 14:39 UTC
