### ISSUE TITLE
Support using module_defaults

### ISSUE THREAD

**Issue by Yannik** [ansible-collections/vmware.vmware_rest#440] opened 2023-11-08 12:50 UTC
##### SUMMARY
The non-rest `vmware` collection supports `module_defaults`, due to its `action_groups` config in https://github.com/ansible-collections/community.vmware/blob/main/meta/runtime.yml.

It would be great if `vmware_rest` would support this too.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
meta

**Comment by mariolenz** [comment] 2023-11-08 18:37
I think this is a valid feature request. However, the modules are generated (originally with with [vmware_rest_code_generator](https://github.com/ansible-collections/vmware_rest_code_generator) but we're working on using [ansible.content_builder](https://github.com/ansible-community/ansible.content_builder)) I wonder if this is something that we should do manually or something we could generate also.

@alinabuzachis @GomathiselviS What do you think?

**Comment by mariolenz** [comment] 2023-11-09 08:58
I think this has already been requested: #361

**Comment by Yannik** [comment] 2023-11-10 11:44
@mariolenz You are right, #361 is requesting the same thing.

I'll leave it up to you whether to continue the discussion there or here.

**Comment by mariolenz** [comment] 2023-12-15 13:09
Since `action_groups` are defined in `meta/runtime.yml` and this file seems to be generated by [ansible.content_builder](https://github.com/ansible-community/ansible.content_builder), I think this has to be implemented there. I've opened a feature request to implement this: ansible-community/ansible.content_builder#75

Therefore I'll close this issue for now. If you think I'm wrong closing it, feel free to open it again :smiley:

**Closed by mariolenz** 2023-12-15 13:09 UTC

**Comment by Yannik** [comment] 2023-12-15 13:25
Makes sense, thanks @mariolenz

**Comment by mariolenz** [comment] 2024-02-23 18:57
> Is there anything that still needs to be done here?

Yep, someone has to re-generate the collection. @alinabuzachis Do you plan to do this?

Alternatively, I've opened #475 as a quick'n'dirty fix. However, even if this is merged I think it's important to release it, too. I consider this a new feature (not a bugfix) so 3.1.0?
